apiVersion: apps/v1
kind: Deployment
metadata:
  name: tawazun-deploy
  namespace: roba-tawazun
  labels:
    app: tawazun
    service: tawazun-svc
    name: RobaAlmehmadi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tawazun
      service: tawazun-svc
  template:
    metadata:
      labels:
        app: tawazun
        service: tawazun-svc
    spec:
      containers:
        - image: robaalmehmadi/tawazun
          name: tawazun
          resources: 
            requests: 
              memory: 250Mi
              cpu: "250m"
            limits:
              memory: 512Mi
              cpu: "500m"
          ports:
            - containerPort: 8080